### ISSUE TITLE
Events outside observation period

### ISSUE THREAD

**Issue by solmazeradat** [OHDSI/Themis#105]
# Events outside observation period

## CDM or THEMIS convention?
THEMIS

## Table or Field level?
NA

## Is this a general convention?
Yes

## Summary of issues

- Forum post was raised after [THEMIS issue #23 20](https://github.com/OHDSI/Themis/issues/23) closure in 2018.  

The old approach:
Before the [THEMIS issue #23 20](https://github.com/OHDSI/Themis/issues/23), when START_DATE and END_DATE must be between OBSERVATION_PERIOD_START_DATE and OBSERVATION_PERIOD_END_DATE we populated SOURCE_VALUE with the name of source table and CONCEPT_ID populate with concept like ‘HISTORY OF…’.
And diagnosis/procedures from patient history was kept in VALUE_AS_STRING and VALUE_AS_CONCEPT_ID fields
field DATE contains OBSERBVATION_PERIOD_START_DATE or date when information about patient history diagnosis/procedures was inputted

The new approach:
After the THEMIS issue above, according to that events can fall outside of an observation period we may use new approach:
keep diagnosis/procedures from patient history in SOURCE_VALUE and CONCEPT_ID fields and use date of diagnosis/procedures from patient history as DATE.

Disadvantage of this approach is that information about data provenance (medical history) would be lost.
Advantage is that we keep real dates of diagnosis/procedures of patient medical history.

So questions are:

For the new approach is it important that diagnosis/procedures are patient history?
Do we need change the approach from the old to new?
Or we may choose approach depending on the percent of records?
Or any other way?

## Summary of answer

- The ETL rule was suggested https://forums.ohdsi.org/t/patient-medical-history-events-outside-observation-period/6945/4?u=solmaz.eradat

- Use of a sliding case https://forums.ohdsi.org/t/patient-medical-history-events-outside-observation-period/6945/6?u=solmaz.eradat

- Application of the rule to the first observation period 

- Link to github issue was mentioned as a final comment in the forum post. 

## Related links

- https://forums.ohdsi.org/t/patient-medical-history-events-outside-observation-period/6945

**Comment by clairblacketer** [comment]
I will take this one as a writer

**Comment by clairblacketer** [comment]
## Issue # and location

- [Themis issue #23](https://github.com/OHDSI/Themis/issues/23)

## Issue summary
In databases with defined enrollment that is used to define the observation period, it is possible for there to be events observed outside of the observation period. What should be done with these events?

## Convention type
Global

## CDM table
NA

## CDM field
NA

## Links to issue discussion

- [OHDSI Forums discussion](https://forums.ohdsi.org/t/patient-medical-history-events-outside-observation-period/6945)
- [CDM Documentation](https://ohdsi.github.io/CommonDataModel/cdm54.html#drug_exposure)   

## Provenance of data
General

## The ratified convention
Events CAN fall out of observation period but they cannot be used to identify people in a cohort (as the index date). 

## Date of ratification/published
Oct 2, 2018

## Downstream implications
No

## Link to DQD check

Yes - plausibleTemporalAfter (page under construction)

## Related conventions/further information
This is related to the convention that every person in the CDM has to have at least one observation period. 

**#Tags**
observation_period
