### ISSUE TITLE
Resolving observation_period_end_date without exact information on a last day

### ISSUE THREAD

**Issue by solmazeradat** [OHDSI/Themis#106]
# Resolving observation_period_end_date without exact information on a last day

## CDM or THEMIS convention?
THEMIS

## Table or Field level?
field

## Is this a general convention?
No

## Summary of issues

- how to populate fields based on the provenance of the visit record as “claims”, “EHR” or any others? 

## Summary of answer

- For the conversion the response suggest the use of the [CDM documentation](https://ohdsi.github.io/CommonDataModel/cdm531.html#OBSERVATION_PERIOD) - Clicking on the link lead to a page with the following text: 

_It is often the case that the idea of Observation Periods does not exist in source data. In those cases, the observation_period_end_date can be inferred as the last Event date available for the Person. In insurance claim data, the Observation Period can be considered as the time period the Person is enrolled with a payer._

- There is also a mention to an ETL conversion which can be chosen at the user discretion. 

## Related links

- https://forums.ohdsi.org/t/resolving-observation-period-end-date-without-exact-information-on-a-last-day/13048/2

**Comment by MaximMoinat** [comment]
## Issue # and location
[Themis issue #106](https://github.com/OHDSI/Themis/issues/106)

## Issue summary
Resolving observation_period_end_date without exact information on a last day

## Convention type
Table

## CDM table
`observation_period`

## CDM field
`observation_period_end_date`

## Links to issue discussion
- [OHDSI Forums discussion](https://forums.ohdsi.org/t/resolving-observation-period-end-date-without-exact-information-on-a-last-day/13048)
- [CDM Documentation](https://ohdsi.github.io/CommonDataModel/cdm54.html#observation_period)   

## Provenance of data
EHR

## The ratified convention
It is often the case that the idea of Observation Periods does not exist in source data. In those cases, the `observation_period_end_date` can be inferred as the last event date available for the person.

## Date of ratification/published
NA

## Downstream implications
This convention can lead to a bias in survival studies. Namely, healthy persons will have shorter observation periods and not contributing to survival time as much.

## Link to DQD check
No

## Related conventions/further information
NA

**#Tags**
observation_period, event, survival

**Comment by adambouras** [comment]
I am working on this ticket and I will get done asap

**Comment by clairblacketer** [comment]
Thanks @adambouras let me know if you need any help!

**Comment by adambouras** [comment]
Hi @clairblacketer , I did `git pull` and I could not find the `observation_period_end_date.md` Could you let  me know if it has been commit by someone else , Thank you

**Comment by clairblacketer** [comment]
Hi @adambouras I'm sorry! I moved this on accident to done as I was finishing up some other ones. Do you need me to add this page?

**Comment by adambouras** [comment]
Yes please @clairblacketer thank you

**Comment by adambouras** [comment]
Thank you, @clairblacketer. I have created the observation_period_end_date, but I was not able to commit my changes.
Could you provide any guidance with this issue Thank you
![Image](https://github.com/OHDSI/Themis/assets/10503610/6509abd6-ebfc-4d1e-b386-153d58a8e675)

**Comment by clairblacketer** [comment]
Hi @adambouras you cannot commit directly to the main branch. You can either clone the repo and create a branch or fork the repo and send a PR through.

**Comment by adambouras** [comment]
Thank you for your guidance @clairblacketer. I have just submitted the PR and I am looking forward to hearing your feedback.

**Comment by MelaniePhilofsky** [comment]
This is documented on the Themis repo page.
