### ISSUE TITLE
What information should put in the field DRUG_EXPOSURE.sig

### ISSUE THREAD

**Issue by jiawei-qian** [OHDSI/Themis#109]
**Issue Name:** What information should put in the field DRUG_EXPOSURE.sig?  Should it only be the drug instruction written by provider? How about other information related to drug use.

**Issue Type:** Multiple ways to store source data in the OMOP CDM

**Description:** In the CDM documentation for DRUG_EXPOSURE.sig, it says:
![image](https://github.com/OHDSI/Themis/assets/84256452/b487cfd4-d87b-4eb2-beb6-2620cbe80343)

In OHDSI Forum, some people asked what information should put in the field DRUG_EXPOSURE.sig.
As an ETL Developer, I also met this situation when I first developed CDM. In the CDM documentation, it says the drug instruction written by the provider. 
However, not all source database has written instruction information (such as: take one pill three times a day after meal).   But there are some other database columns which have related drug use information such as: frequency of medication (st, qd, bid, tid, q12h, qn, qod, q2w), drug route (Intravenous, Oral, Sublingual, Inhalation, Transdermal, Injection, Nasal).    These information is not written by provider.

Although the sig field data won't be used in standardized analysis and should be the written instruction (meaning), other database columns also have useful drug use information which may be helpful for CDM users in the future.    Otherwise, we would lose instruction information in CDM and no other CDM fields can store data such as frequency of medication.

![image](https://github.com/OHDSI/Themis/assets/84256452/7216ee17-0d2e-43e8-92e9-ae76c146a3f5)

**Related forum post:** https://forums.ohdsi.org/t/what-does-the-field-sig-in-the-table-drug-exposure-means/8097

**Suggested solution:**
1. Is it possible to add/update CDM convention for sig field in CDM documentation to also allow storing other related drug use information which are not written by provider, if source database doesn't have written instruction information.   This would help save valuable data in CDM table as much as we can.
2. Is it possible to add example of sig field in CDM documentation.      (Some people may be confused by the meaning of sig and what can be stored especially for non-English speaking people)

**Reported By:** Jiawei Qian

**Comment by MelaniePhilofsky** [comment]
@jiawei-qian The drug_exposure.sig field is a field found in some source data. Therefore, we shouldn't change the field meaning for some datasets, since there is no way the analyst will know the true meaning of the field. If you would like to add an additional field to the CDM for other related information or attributes of a drug exposure, you should open an issue in the CDM GitHub repository.
I think updating the CDM documentation for the drug_exposure.sig field would be helpful. I will move this issue to the CDM repo.

**Comment by cgreich** [comment]
I put a placeholder CDM issue in: https://github.com/OHDSI/CommonDataModel/issues/689. Will need to be developed into a proper proposal. Let's see if @tiozab could be interested in joining.

**Comment by MelaniePhilofsky** [comment]
Thank you, @cgreich! Since there is now an open issue in the CDM GitHub, I will close this one.
