### ISSUE TITLE
Domains and the Measurement Table

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#119]
# Domains and the Measurement Table

## CDM or THEMIS convention?
THEMIS

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues

- On the old wiki site, this is mentioned "Valid Measurement Concepts (measurement_concept_id) belong to the 'Measurement' domain, but could overlap with the 'Observation' domain. This is due to the fact that there is a continuum between systematic examination or testing (Measurement) and a simple determination of fact (Observation)."  

## Summary of answer

- I am not seeing the "Observation" domain in our MEASUREMENT tables however I am seeing other domains like "Metadata" and "Note".  If something like this is true we could made additional suggested documenting this.  @clairblacketer or @burrowse is there a rule that everything should be measurement domain or can some other domains sneak in?		

## Related links

- https://www.ohdsi.org/web/wiki/doku.php?id=documentation:cdm:measurement

## Other comments/notes

- None

**Comment by clairblacketer** [comment]
Thanks @ericaVoss I think what is going on in our databases is that we have some manual mappings that put the records in the MEASUREMENT table with the wrong domain. We are specific about the requirement that records in the MEASUREMENT table must belong to the measurement domain so I am not sure what we meant on the wiki about the overlap with the observation domain. I don't think we should create a repo page for this one.
