### ISSUE TITLE
Granular vs Total Cost

### ISSUE THREAD

**Issue by aostropolets** [OHDSI/Themis#12]
TYPE | NOTES
-- | --
ITEM | How to handle granular vs total cost from claims data? 
FORUM POST | http://forums.ohdsi.org/t/proposal-for-cost-table-adjustment/1842/21      https://github.com/OHDSI/CommonDataModel/issues/81
SOLUTION | Use cost_type_concept_ids.  Class = “summary” will denote “total cost” and class = “detail” will denote granular costs.
NEXT STEPS | update CDM Wiki for COST table

**Comment by amahesh11** [comment]
This issue will be on hold until the  CDM v6 is available. Create a new label to indicate "on hold"

**Comment by ericaVoss** [comment]
Agreement that CDM V6.0.0 addresses this.
