### ISSUE TITLE
How to populate death_datetime field when month, day, or time are not in source data

### ISSUE THREAD

**Issue by assimilateDave** [OHDSI/Themis#121]
#Populating death_datetime when missing some source data elements 

## CDM or THEMIS convention?
THEMIS Issue - currently documented in the CDM webpage
https://ohdsi.github.io/CommonDataModel/cdm54.html#death

## Table or Field level?
death_datetime field

## Is this a general convention?
No

## Summary of issues

- Item is similar and related to the death_date fieldl see issue - https://github.com/orgs/OHDSI/projects/27/views/1?pane=issue&itemId=58744858
- Time, Day, month, and year are expected in the death_datetime field.
- Some source data may not have complete datestamp of the deceased persons death date. An approximation of that date should be used.
- This issue was discussed thoroughly and ratified and could be documented as a Themis convention instead of in the CDM since it may not be applicable to all use cases and data sources.

## Summary of answer

- This directive is included in the CDM 5.4 on death_date.  This could be incorporated for the Themis guidelines for death_datetime.  The second bullet is the current CDM 5.4 directive for this field.  The two should be combined for the death_datetime directive. 
  -  If the precise date include day or month is not known or not allowed, December is used as the default month, and the last day of the month the default day.
  - If not available set time to midnight (00:00:00)

## Related links

- https://ohdsi.github.io/CommonDataModel/cdm54.html#death
- https://github.com/OHDSI/CommonDataModel/issues/210

## Other comments/notes

-

**Comment by MelaniePhilofsky** [comment]
@clairblacketer Agree
