### ISSUE TITLE
How to populate days_supply when it is missing in the source data

### ISSUE THREAD

**Issue by burrowse** [OHDSI/Themis#125]
# How to populate days_supply when days supply is missing the source data

## CDM or THEMIS convention?
Themis

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues

- There are instances when days_supply for a drug is missing in the source data

## Summary of answer

- The CDM documentation states: The field should be left empty if the source data does not contain a verbatim days_supply, and should not be calculated from other fields.

## Related links

- CDM documentation: https://ohdsi.github.io/CommonDataModel/cdm54.html#drug_exposure
- Forum posts: https://forums.ohdsi.org/t/days-supply-yet-again/4741/16
- Themis repo ratified convention: https://github.com/OHDSI/Themis/issues/76

**Comment by clairblacketer** [comment]
## Issue # and location

- [Themis issue #125](https://github.com/OHDSI/Themis/issues/125)
 
## Issue summary
How should days_supply be populated when it is missing from the source data?

## Convention type
Table

## CDM table
`drug_exposure`

## CDM field
`days_supply`

## Links to issue discussion

- [OHDSI Forums discussion](https://forums.ohdsi.org/t/days-supply-yet-again/4741/16)
- [THEMIS issue #76](https://github.com/OHDSI/Themis/issues/76)   

## Provenance of data
General

## The ratified convention
The field should be left empty if the source data does not contain a verbatim days_supply, and should not be calculated from other fields.

## Date of ratification/published
Sept 24, 2021 (CDM v5.4 release date)

## Downstream implications
No

## Link to DQD check
No

## Related conventions/further information
NA

**#Tags**
drug_exposure, days_supply
