### ISSUE TITLE
Missing visit end datetime

### ISSUE THREAD

**Issue by solmazeradat** [OHDSI/Themis#128]
# Missing visit end datetime

## CDM or THEMIS convention?
THEMIS

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues

- We have visit start datetime data at the source, but not end datetime. Is it ok to leave visit_end_datetime null when visit_start_datetime is populated?

## Summary of answer
 
Clarified during Friday call. See point Below: 
- ok to leave visit_end_datetime null when visit_start_datetime is populated

## Related links

- forum post - https://forums.ohdsi.org/t/ehr-data-to-omop-cdm-work-group/5222/255?u=solmaz.eradat

## Other comments/notes

- Please use this section to add any other relevant notes or comments. (i.e. if links are not working, something is out of date or  deprecated)

**Comment by MelaniePhilofsky** [comment]
## Issue # and location

## Issue summary
We have visit start datetime data at the source, but not end datetime. Is it ok to leave visit_end_datetime null when visit_start_datetime is populated?

## Convention type
Table

## CDM table
`visit_occurrence`

## CDM field
`visit_end_datetime`

## Links to issue discussion
 

## Provenance of data
General

## The ratified convention
visit_end_datetime is not a required field. Therefore, it is ok to leave visit_end_datetime null when visit_start_datetime is populated.

## Date of ratification/published
NA

## Downstream implications
NA

## Link to DQD check

## Related conventions/further information

**#Tags**
visit_occurrence, visit_end_datetime, date, datetime
