### ISSUE TITLE
Can drug_type_concept_id tells us who (physicians, nurse practitioner or doctor) administer the drug

### ISSUE THREAD

**Issue by jiawei-qian** [OHDSI/Themis#132]
# Can drug_type_concept_id tells us who (physicians, nurse practitioner or doctor) administer the drug

## CDM or THEMIS convention?
CDM

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues
1. There are many values for representing drug_type_concept_id in DRUG_EXPOSURE table. For concept id: 43542358 (Physician administered drug(identified from EHR observation)), are all drugs administered by physicians or there is a distinction (Nurse practitioner vs Doctor)?

## Summary of answer
1. Christian: No, drug_type_concept_id declares the source of the information. Not the source of the act. In order to find who administered the drug, need to look up in the PROVIDER table record linked to the DRUG_EXPOSURE record through the provider_id field.

## Related links
OHDSI Forum: https://forums.ohdsi.org/t/drug-type-concept-id-values-from-drug-exposure-table-what-do-they-represent-is-there-overlap/12143

## Other comments/notes
I see the concept id 43542358 is non-standard now in ATHENA. Maybe it was standard when the question was raised. Here, I think this concept can be used as reference because it has "Physician" word inside which may confuse some CDM users.

**Comment by jiawei-qian** [comment]
Sorry Clair, I think it is a CDM issue.  I moved it to the THEMIS issue incorrectly.  Could you help move it into CDM if you think it's a CDM convention.

**Comment by MelaniePhilofsky** [comment]
I am going to close this issue since this references an old conversation and this concept_id is no longer standard. The concept_id has been replaced by an updated list of concept_ids in the "Type" domain.
