### ISSUE TITLE
How to populate drug_exposure.verbatim_end_date

### ISSUE THREAD

**Issue by burrowse** [OHDSI/Themis#134]
# How to populate drug_exposure.verbatim_end_date

## CDM or THEMIS convention?
Themis

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues

- There are several dates "end" dates in the drug_exposure table drug_exposure_end_date, drug_exposure_end_datetime and verbatim_end_datetime. It is unclear how/when verbatim_end_date should be stored.
- 
## Summary of answer

- It represents the "discontinue day" or date the physician explicitly stopped the medication
- Populate only when it is directly defined in the source as a date. If this is not available, leave the field blank

## Related links

- CDM Documentation: https://ohdsi.github.io/CommonDataModel/cdm54.html#drug_exposure
- Details captured as a part of a drug_exposure.quantity conversation: https://forums.ohdsi.org/t/drug-exposure-quantity-recalculation/9607/4
- Question about how to populate verbatim_end_date: https://forums.ohdsi.org/t/the-difference-between-verbatim-end-date-and-drug-exposure-end-date-in-drug-exposure-table-of-v5-2/3281/2

**Comment by MelaniePhilofsky** [comment]
## Issue # and location
- [CDM_documentation](https://ohdsi.github.io/CommonDataModel/cdm54.html#drug_exposure)


## Issue summary
There are several "end" dates in the drug_exposure table: drug_exposure_end_date, drug_exposure_end_datetime and verbatim_end_datetime. It is unclear how/when verbatim_end_date should be stored.

## Convention type
Table

## CDM table
`drug_exposure`

## CDM field
`verbatim_end_date`

## Links to issue discussion
- [OHDSI Forums discussion](https://forums.ohdsi.org/t/drug-exposure-quantity-recalculation/9607/4)
- [OHDSI Forums discussion](https://forums.ohdsi.org/t/the-difference-between-verbatim-end-date-and-drug-exposure-end-date-in-drug-exposure-table-of-v5-2/3281/2)

## Provenance of data
General

## The ratified convention
verbatim_end_date represents the "discontinue day" or date the physician explicitly stopped the medication.
Populate the field only when it is directly defined in the source as a date. If this is not available, then leave the field blank.

## Date of ratification/published
NA

## Downstream implications
NA

## Link to DQD check
NA

## Related conventions/further information


**#Tags**
drug_exposure, verbatim_end_date, date

**Comment by clairblacketer** [comment]
https://github.com/OHDSI/Themis/pull/152
