### ISSUE TITLE
Should drug_exposure.quantity be recalculated if a patient discontinues a drug

### ISSUE THREAD

**Issue by burrowse** [OHDSI/Themis#135]
# Should drug_exposure.quantity be recalculated if a patient discontinues a drug

## CDM or THEMIS convention?
Themis

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues

- Patients can choose to discontinue drugs, which may make the quantity of a drug look inconsistent with the duration of a drug for a given patient when looking at start and end dates
- The question then becomes, should drug_exposure.quantity be recalculated if a patient discontinues a drug?

## Summary of answer

- From forum discussion, quantity should represent the actual quantity of the drug dispensed and should not be recalculated/inferred based on dates if a patient discontinues a drug.

## Related links

- CDM Documentation: https://ohdsi.github.io/CommonDataModel/cdm54.html#drug_exposure
- Forum Post: https://forums.ohdsi.org/t/drug-exposure-quantity-recalculation/9607/6

**Comment by MelaniePhilofsky** [comment]
## Issue # and location

- [CDM Documentation](https://ohdsi.github.io/CommonDataModel/cdm54.html#drug_exposure)
- [Forum](https://forums.ohdsi.org/t/drug-exposure-quantity-recalculation/9607/6)

## Issue summary

Patients can choose to discontinue drugs, which may make the quantity of a drug look inconsistent with the duration of a drug for a given patient when looking at start and end dates
The question then becomes, should drug_exposure.quantity be recalculated if a patient discontinues a drug?

## Convention type
Table

## CDM table
`Drug_Exposure`

## CDM field
`quantity`

## Links to issue discussion
- [CDM Documentation](https://ohdsi.github.io/CommonDataModel/cdm54.html#drug_exposure)
- [Forum](https://forums.ohdsi.org/t/drug-exposure-quantity-recalculation/9607/6)

Format as follows:
- [OHDSI Forums discussion](https://forums.ohdsi.org/t/drug-exposure-quantity-recalculation/9607)
- [CDM Documentation](https://ohdsi.github.io/CommonDataModel/cdm54.html#drug_exposure)   

## Provenance of data
All

## The ratified convention
The quantity should represent the actual quantity of the drug dispensed and should not be recalculated/inferred based on dates if a patient discontinues a drug.

## Date of ratification/published
February 24, 2020

## Downstream implications
No

## Link to DQD check
No

## Related conventions/further information


**#Tags**
drug exposure, quantity, calculation, infer

**Comment by clairblacketer** [comment]
@MelaniePhilofsky I am going to open this back up until it is built into the repo

**Comment by clairblacketer** [comment]
https://github.com/OHDSI/Themis/pull/151
