### ISSUE TITLE
Duplicate Drugs on Same Day

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#14]
TYPE | NOTES
-- | --
ITEM | What should someone do if duplicate drugs are reported on the same day?
FORUM POST | http://forums.ohdsi.org/t/duplicate-drugs-themis-wg3/4101
SOLUTION | If a patient has multiple records on the same day for the same drug or procedures the ETL should not dedupe them unless there is probable reason to believe the item is a true data duplicate.
NEXT STEPS | Work with @clairblacketer  and CDM WG to have this added to the DRUG_EXPOSURE part of the WIKI under convensions.  https://github.com/OHDSI/CommonDataModel/wiki/DRUG_EXPOSURE

**Comment by PRijnbeek** [comment]
Indeed bad idea to remove these. This happens all the time and can be valid. Let the analytical step decide if they want to stockpile or not etc.
