### ISSUE TITLE
What to do with SOURCE_VALUE Fields?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#15]
TYPE | NOTES
-- | --
ITEM | Do we want to or not want to standardize what goes into various source_value fields.  Every table has one and currently is free to use in any way the ETLer wants.  There is standardization under the SOURCE_CONCEPT_ID field.  However, it only works if people (i) use it, (ii) if the source code is covered by a Standardized Vocabulary, or (iii) if people make their own concepts (the so-called 2-Billionaires).
FORUM POST | http://forums.ohdsi.org/t/themis-question-what-do-people-put-in-the-source-value-fields/4092/15
SOLUTION | Verbatim information from the source data, typically used in ETL to map to CONCEPT_ID, and not to be used by any standard analytics. There is no standardization for these fields and these columns can be used as the local CDM builders see fit. A typical example would be an ICD-9 code without the decimal from an administrative claim as condition_source_value = '78702' which is how it appeared in the source.
NEXT STEPS | Work with CDM WG to update the "Data Model Conventions" part of the wiki in the SOURCEVALUE description cell and change it to the below statement. <br/> https://github.com/OHDSI/CommonDataModel/wiki/Data-Model-Conventions

**Comment by PRijnbeek** [comment]
Agree to not push for standardization of source_values this will be a hell for us in Europe :)
