### ISSUE TITLE
How should we handle multiple deaths on different days

### ISSUE THREAD

**Issue by jiawei-qian** [OHDSI/Themis#155]
# How should we handle multiple deaths on different days

## CDM or THEMIS convention?
THEMIS

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues
1. How should we handle multiple deaths on different days?

## Summary of answer
1. Only one death date per individual can be used. If a patient has clinical activity (e.g. prescriptions filled, labs performed, etc) more than 60+ days after death you may want to drop the death record as it may have been falsely reported. If multiple records of death exist on multiple days you may select the death that you deem most reliable (e.g. death at discharge) or select the latest death date.

## Related links
Themis GitHub: https://github.com/OHDSI/Themis/issues/6
OHDSI Forum: https://forums.ohdsi.org/t/multiple-deaths-on-different-days/4552

**Comment by MaximMoinat** [comment]
## Issue # and location
[Themis issue #155](https://github.com/OHDSI/Themis/issues/155)

## Issue summary
Handling multiple deaths on different days

## Convention type
Table

## CDM table
`death`

## CDM field
NA

## Links to issue discussion
- [OHDSI Forums discussion](https://forums.ohdsi.org/t/multiple-deaths-on-different-days/4552)
- [Themis GitHub](https://github.com/OHDSI/Themis/issues/6)

## Provenance of data
General

## The ratified convention
Only one death date per individual can be used. If a patient has clinical activity (e.g. prescriptions filled, labs performed, etc) more than 60+ days after death you may want to drop the death record as it may have been falsely reported. If multiple records of death exist on multiple days you may select the death that you deem most reliable (e.g. death at discharge) or select the latest death date.

## Date of ratification/published
Some previously ratified conventions might not contain this data. If unable to find a date, then use the current date as the date of publication in the Themis repository.

## Downstream implications
Does the OHDSI community need to update OHDSI tools or methods based on the publication of this convention? If yes, which tools or methods?

## Link to DQD check
Is this a DQD check? Make your best guess based on the descriptions available on  https://ohdsi.github.io/DataQualityDashboard/articles/checkIndex.html. Do not spend more than 5 minutes on this activity.

Format as follows:
Yes - [isRequired](https://ohdsi.github.io/DataQualityDashboard/articles/checks/isRequired.html).

## Related conventions/further information
Other helpful information, if needed. i.e. related conventions, queries to evaluate source or CDM data, or any additional information

**#Tags**
Any words, phrases that allow users to more easily find this convention in the library.
