### ISSUE TITLE
How to populate payer_plan_period.payer_concept_id based on plan type in the source

### ISSUE THREAD

**Issue by burrowse** [OHDSI/Themis#156]
# How to populate payer_plan_period.payer_concept_id based on plan type in the source

## CDM or THEMIS convention?
Themis

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues

- There are outstanding questions on the forum on how to populate payer_concept_id based on plan type.
- For example, this forum post asks the question if concept_id 327 (“Private Health Insurance” the parent of commercial claims) or 328 (“Private Health Insurance - Managed Care”) should be used instead of 0 for "commercial claim and encounter" datasets where "plan type" blank. 
- Another post asks about specific guidance for:
    -  Plan types of "Point of Service" and "Point of Service with capitation" mapping to 331 "Commercial Managed Care - Point of Service"
   - Commercial Claims and Encounters and Medicare datasets mapping to 284 "Medicare Point of Service"  

## Summary of answer

- Based on the forum, there doesn't appear to be general guidance on how these should be mapped for the payer_concept_id
- There could be general guidance provided on how to populate payer_plan_period.pay_concept_is based on the plan_type and/or the dataset type 

## Related links

- Forum post about commercial claim and encounter datasets where plan type is blank: https://forums.ohdsi.org/t/concept-for-payer-in-payer-plan-period-where-type-of-plan-is-undefined/10385
- Additional forum post about specific plan types and datasets: https://forums.ohdsi.org/t/concepts-for-payer-and-plan-on-cdm-payer-plan-period-table/8535

## Other comments/notes

- This topic needs more discussion to provide guidance to the community.

**Comment by MelaniePhilofsky** [comment]
Archiving this issue. Please reopen this issue if there are still questions.
