### ISSUE TITLE
How should we handle quantities of ‘0’ in Devices and Procedures

### ISSUE THREAD

**Issue by jiawei-qian** [OHDSI/Themis#158]
# How should we handle quantities of ‘0’ in Devices and Procedures

## CDM or THEMIS convention?
THEMIS

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues
1. How should we handle quantities of ‘0’ in Devices and Procedures?

## Summary of answer
1. Default quantities of ‘0’ to ‘1’. If there is a record in the source then we can assume this occurred at least once. (Update the PROCEDURE_OCCURRENCE and DEVICE WIKI pages under conventions.)

## Related links
Themis GitHub: https://github.com/OHDSI/Themis/issues/26
Themis GitHub: https://github.com/OHDSI/Themis/issues/3
OHDSI Forum: https://forums.ohdsi.org/t/quantities-of-0-for-devices-and-procedures/4614

## Other comments/notes
@clairblacketer, @MelaniePhilofsky, The User Guide and ETL Conventions are empty for DEVICE_EXPOSURE.quantity field. For PROCEDURE_OCCURRENCE.quantity field, it has these information.
Is it possible to add the information for DEVICE_EXPOSURE.quantity field?

**Comment by MelaniePhilofsky** [comment]
Yes, thank you for bringing this to our attention. @clairblacketer Should this be in the CDM documentation since the rule is to only have records in the CDM when a clinical event has occurred?

**Comment by clairblacketer** [comment]
Thanks @MelaniePhilofsky and @jiawei-qian I like the idea of putting in a default of '1' in device_exposure if we can be sure the exposure occurred. I think we should also put the same language like we put in Drug_Exposure where we say if there is a negative value in quantity coming from the source the record should be dropped as we cannot be sure the exposure occurred.
