### ISSUE TITLE
Negative Integers in MEASUREMENTS

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#16]
TYPE | NOTES
-- | --
ITEM | What should be done with negative integers for MEASUREMENTS?
FORUM POST | http://forums.ohdsi.org/t/negative-values-in-lab-test-records/4012
SOLUTION | Only allow values for negative measurements (see list below).  If you have negative values for positive measurements, then set it to NULL.<br><br>**Negative Measurements**<br>1925-7-Base excess in Arterial blood by calculation<br>1927-3-Base excess in Venous blood by calculation<br> 8632-2 - QRS-Axis <br>11555-0 - Base excess in Blood by calculation <br> 1926-5 - Base excess in Capillary blood by calculation <br>28638-5 - Base excess in Arterial cord blood by calculation <br> 28639-3 - Base excess in Venous cord blood by calculation |	mmol.L:[-10,-2]
NEXT STEPS | 1. Work to develop an exception list (e.g.  1925-7-Base excess in Arterial blood by calculation, RANGE: mmol.L:[-2,+2], https://s.details.loinc.org/LOINC/1925-7.html), <br/><br/>  2. Update ACHILLES (@vojtechhuser) to do a warning on non-exempt tests that are negative. <br/><br/>  3. Work with CDM WG to document both the exception list and above text in the VALUE_AS_NUMBER column. https://github.com/OHDSI/CommonDataModel/wiki/MEASUREMENT

**Comment by eldarallakhverdiiev** [comment]
There is a bunch of codes reflecting bone densitometry, which values(T-score, Z-score) can be negative as well:
`SELECT *
FROM concept
WHERE concept_name LIKE 'DXA%'
AND   domain_id = 'Measurement'`

**Comment by ericaVoss** [comment]
```SQL
SELECT * 
FROM concept 
WHERE (concept_name LIKE 'DXA%' 
AND   domain_id = 'Measurement'
AND STANDARD_CONCEPT = 'S')
OR CONCEPT_ID IN (3003396,3002032,3006277,3012501,3003129,3004959,3007435)
ORDER BY CONCEPT_NAME, CONCEPT_CODE
```
