### ISSUE TITLE
Duplicate Providers?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#161]
# Duplicate Providers?

## CDM or THEMIS convention?
THEMIS

## Table or Field level?
TABLE

## Is this a general convention?
PROVIDER table

## Summary of issues

- There is conversation online on what to do when multiple values (i.e., PROVIDER_NAME, NPI, DEA, SPECIALTY_SOURCE_VALUE, etc.) are given for a second PROVIDER.  Asserting the THEMIS rule that each provider only get one record is important.

## Summary of answer

This is the THEMIS rule:
[Multiple Provider Specialities #43](https://github.com/OHDSI/Themis/issues/43)

`In the table, each provider should appear only once; duplication is not allowed. If a provider specializes in more than one area, record their primary or most frequently practiced specialty.`

## Related links

- [Multiple Provider Specialities #43](https://github.com/OHDSI/Themis/issues/43)
  - This states we can only have one record
- [CDM GitHub.io PROVIDER](https://ohdsi.github.io/CommonDataModel/cdm53.html#provider)
- [Provider table ](https://forums.ohdsi.org/t/provider-table/5494)
 - Seems to be a fair amount of discussion about what happens when you have multiple records for one provider with same NPI

## Other comments/notes

- N/A

**Comment by clairblacketer** [comment]
Thanks @ericaVoss and @jiawei-qian. Given the wording of this convention I am going to put it in the CDM documentation since it should apply to every CDM
