### ISSUE TITLE
Mapping from source conditions to standard concepts

### ISSUE THREAD

**Issue by askanter** [OHDSI/Themis#162]
# Mapping from source conditions to standard concepts

## CDM or THEMIS convention?
THEMIS

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues

Mapping of disease, diagnosis or problem concepts to the condition table may not be 1:1 with standard concepts or might not be synonymous

## Summary of answer

Condition concepts are primarily mapped to SNOMED CT for standard concepts. Some concepts like Oncology diagnoses might be mapped to ICD-O. When mapping, source concepts should be mapped fully to standard concepts even if it requires more than one code. If the source system already maps to standard codes use them, rather than mapping first to ICD and then map to SNOMED.

## Related links

(https://forums.ohdsi.org/t/duplicate-concept-ids-for-different-condition-concept-ids/9336) 
https://forums.ohdsi.org/t/one-condition-maps-to-2-condition-concept-id-what-to-do/2968
https://forums.ohdsi.org/t/family-history-extension-model/17947/7

## Other comments/notes

- Please use this section to add any other relevant notes or comments. (i.e. if links are not working, something is out of date or  deprecated)

**Comment by clairblacketer** [comment]
Thanks @askanter we wlll create a general convention page for this one on the themis repo
