### ISSUE TITLE
How to link readmission to the primary to primary admission using the field preceding_visit_occurrence_id in the Visit_occurrence table?

### ISSUE THREAD

**Issue by solmazeradat** [OHDSI/Themis#167]
# How to link readmission to the primary to primary admission using the field preceding_visit_occurrence_id in the Visit_occurrence table?

## CDM or THEMIS convention?
THEMIS

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues

- In some databases we can have information about patient readmission to hospital after surgery admission that we would like to store in CDM.
- Using `visit_occurrence.preceding_visit_occurrence_id` , that can be filled with visit_occurrence_id of corresponding surgery admission visit. This way seems elegant but I’m not sure
that it’s correct as due to CDM documentation it can be used to link a visit IMMEDIATELY preceding.
- lets say we have sequence of visits 1,2,3,4, where 1 is a surgery admission visit, 4 readmission visit. 2 and 3 are some other visits happened between 1 and 4 and are not related to surgery admission visit.

- Is it legit for visit 4 to use preceding_visit_occurrence_id = 1 to link primary admission with readmission?

## Summary of answer

**Author 1**
- the original stated intent of `visit_occurrence.preceding_visit_occurrence_id` was to capture the visit immediately preceding the current visit record. In reality I take this to mean that the field is attempting to capture readmissions. Readmissions are notoriously tricky to logically define because I think of them as strictly inpatient artifacts so if a person was in the hospital, then had an outpatient follow-up, and then had another inpatient stay a few days later, you could make the argument that preceding_visit_occurrence_id should be the inpatient stay and not the outpatient inbetween. With that being said, I don’t believe this field is being used currently in standard analytics so this is our chance to refine the definition a bit.

**Author 2**
- Not sure what this would do. The Preceding Visit field is used to chain together a sequence of Visits that from the patient perspective would be considered one long treatment. Readmission is the opposite: It says the patient was sent home, but then it turned out that was too early. So, readmission is admission after a non-adjacent Visit situation. If you smooshed it together you would not be able to find these.

**Author 3 provides example of cancer patient** 
- There can be several visits within a short period of time after surgery and only one of them is actually readmission related to surgery ( let’s say it was cancer surgery and there were several visits for chemotherapy etc. and one - readmission). So it’s not enough just to look for new visits. From source data I do know for sure what of the following visits was readmission related to the surgery and I need to have corresponding ‘flag’ in CDM.

**Summery of last comment in post**
- The author doesn't have a specific solution on defining "readmissions" 
- They raise concerns about introducing another "meta-concept" like "readmission." This would add another layer of context to existing records (visits or observations), requiring users to look in multiple places to find relevant information (e.g., the actual condition vs. a separate "readmission observation").
- While acknowledging their previous suggestion of using a "value_as_concept" to capture readmissions, the author now worries about having clinical observations scattered across two locations.

They propose an alternative approach:

- Define concepts for "readmission" observations.
- Use existing concepts for "condition occurrence" and "readmission" observation within the same visit (or a specific timeframe) to identify readmission studies. This wouldn't pinpoint the specific reason for readmission but would provide context.

## Related links

- forum post - https://forums.ohdsi.org/t/visit-occurrence-preceding-visit-occurrence-id/11943

## Other comments/notes

- Please use this section to add any other relevant notes or comments. (i.e. if links are not working, something is out of date or  deprecated)

**Comment by MelaniePhilofsky** [comment]
Closing this issue. Preceding_visit_occurrence_id in the Visit_occurrence table is already defined in the CDM documentation. Please reopen if you need guidance.
