### ISSUE TITLE
How to handle geographical or year-based multiplier tables?

### ISSUE THREAD

**Issue by aostropolets** [OHDSI/Themis#17]
TYPE | NOTES
-- | --
ITEM | How to handle geographical or year-based multiplier tables?
FORUM POST | http://forums.ohdsi.org/t/geographical-year-based-multiplier/4571
SOLUTION | Currently, the CDM does not handle this information.  
NEXT STEPS | A proposal has to be submitted to the CDM Working Group for storing this information.

**Comment by PRijnbeek** [comment]
Can someone explain what we mean with a multiplier table? (Clearly not something we ever had to use.)

**Comment by alondhe** [comment]
@PRijnbeek, I asked about this as well in the forums, see below post. I'm not sure this item has enough traction or need at this time, so perhaps we should remove it from 60 day review and re-assign to either "invalid" or "won't fix".

```
IIRC, this issue may have originated during the first F2F about the supplementary cost modifier table Optum provides us that can be used to render costs relative to a specific year.

I thought we had settled on calling this a non-issue for Themis, that it's something to be handled at analysis time only.

Not sure -- is there some other issue at play here?
```

**Comment by amahesh11** [comment]
This is no longer an issue. This issue should be handled during analysis. This is not a requirement for CDM or ETL. Create a new label to indicate this is not an issue or close this.

**Comment by ericaVoss** [comment]
Closing because we don't understand the use case for the multiplier and the geo issue has been handled.
