### ISSUE TITLE
Drug_exposure_end_date for vaccine records

### ISSUE THREAD

**Issue by crabcakeworld** [OHDSI/Themis#170]
### CDM or THEMIS convention?
THEMIS

### Table or Field level?
Field

### Is this a general convention?
Not sure.

### Summary of issues
For the vaccine records in Drug_Exposure table, we use this convention: 
drug_exposure_end_date = drug_exposure_start_date 

### Summary of answer
Author: Qi Yang (qi.yang1@iqvia.com)

Standard concepts of vaccine record in Drug_Exposure table can be one of the following two vocabularies: CVX or RxNorm (Extension). 

_For CVX, use following query to get all concepts:_

```
select *
from CONCEPT
where vocabulary_id = 'CVX'
and standard_concept = 'S'
and concept_id not in
(
40213270 , -- AS03 Adjuvant
40213272 , -- botulinum antitoxin
40213212 , -- Rho(D) Immune globulin - IM
40213213 , -- Rho(D) Immune globulin- IV or IM
2
40213215 , -- rabies immune globulin
40213256 , -- varicella zoster immune globulin (Investigational New Drug)
40213297 , -- Hepatitis A immune globulin
40213323 , -- immune globulin, intramuscular
40213324 , -- immune globulin, unspecified formulation
40213325 -- immune globulin, intravenous
)
```

_For RxNorm(Extension), use following query to get all concepts:_

```
select b.*, a.max_levels_of_separation
from CONCEPT_ANCESTOR a join CONCEPT b on a.descendant_concept_id = b.concept_id
where a.ancestor_concept_id = 21601278  -- VACCINES (ATC 2nd)
and standard_concept = 'S'
order by a.max_levels_of_separation
```

_For all the vaccine records in Drug_Exposure table, use following query:_

```
with cte_standard_vaccine_concept as
(
3
select concept_id
from
(
select b.concept_id
from CONCEPT_ANCESTOR a join CONCEPT b on a.descendant_concept_id = b.concept_id
where a.ancestor_concept_id = 21601278
and standard_concept = 'S'
-- order by a.max_levels_of_separation
UNION
select concept_id
from CONCEPT
where vocabulary_id = 'CVX'
and standard_concept = 'S'
and concept_id not in
(
40213270 , -- AS03 Adjuvant
40213272 , -- botulinum antitoxin
40213212 , -- Rho(D) Immune globulin - IM
40213213 , -- Rho(D) Immune globulin- IV or IM
40213215 , -- rabies immune globulin
40213256 , -- varicella zoster immune globulin (Investigational New Drug)
40213297 , -- Hepatitis A immune globulin
40213323 , -- immune globulin, intramuscular
40213324 , -- immune globulin, unspecified formulation
40213325 -- immune globulin, intravenous
)
) c
)
select a.*
from N3Cdatabase.DRUG_EXPOSURE a join cte_standard_vaccine_concept b
on a.drug_concept_id = b.concept_id
```

For these records, the drug_exposure_end_date can be set to equal to drug_exposure_start_date 

### Related links
This has not been rectified. But we use the logic in our firm.

### Other comments/notes
None.

**Comment by MelaniePhilofsky** [comment]
Hello @crabcakeworld,
The Summary of the Issue "For the vaccine records in Drug_Exposure table, we use this convention:
drug_exposure_end_date = drug_exposure_start_date", already has guidance. What to do when a data source lacks a drug stop or end date.

The Summary of the Answer, is more about how to find these concepts in the concept table. It's good guidance, we don't want to lose this. However, Themis isn't the correct place for guidance on how to retrieve concept_ids based on your use case. This belongs in the [OHDSI Query Library](https://data.ohdsi.org/QueryLibrary/). I'm unsure who owns this project. You should post on the forums, @crabcakeworld

**Comment by MelaniePhilofsky** [comment]
The ratified convention for administered drugs is to set drug_end_date = drug_start_date when the source data doesn't contain an end date.
