### ISSUE TITLE
Should we also add a record to CONDITION_OCCURRENCE table for each cause of death

### ISSUE THREAD

**Issue by jiawei-qian** [OHDSI/Themis#175]
# Should we also add a record to CONDITION_OCCURRENCE table for each cause of death

## CDM or THEMIS convention?
THEMIS

## Table or Field level?
Table

## Is this a general convention?
No

## Summary of issues
1. If a cause of death belongs to ‘Condition’ domain should we add a record, associated with this code, to cdm Condition_occurrene table as well?

2. Would the diagnosis code for that condition only be found in DEATH because it was a cause of death, or would it be found in CONDITION_OCCURENCE on the same date as they died?

## Summary of answer
1. **Christian**: Yes, both. The patient had that Condition before he died, so it’s legitimate to have it in the Condition table like all others.

2. **Christian**: Yes, all those Conditions, including the actual killer, are in the Condition table. But only one should go into the Death table.

## Related links
OHDSI Forum (answer to question 1): https://forums.ohdsi.org/t/condition-occurrence-death-diagnoses/2609/6
OHDSI Forum (answer to question 2): https://forums.ohdsi.org/t/condition-occurrence-death-diagnoses/2609/30

## Other comments/notes
I am not sure if this answer from Christian is ratified. But I don't see any objections from this OHDSI Forum post.

**Comment by clairblacketer** [comment]
@jiawei-qian I don't believe this is a ratified convention, we just want to put in the repo ratified conventions. I will move this to needs more work
