### ISSUE TITLE
Where should we store DRG codes?

### ISSUE THREAD

**Issue by aostropolets** [OHDSI/Themis#19]
TYPE | NOTES
-- | --
ITEM | Where should we store DRG codes?
FORUM POST | http://forums.ohdsi.org/t/most-appropriate-omop-table-to-house-drg-information/1591/8
SOLUTION | DRGs should be stored in the COST table using the DRG_CONCEPT_ID and DRUG_SOURCE_VALUE columns.
NEXT STEPS | Vocabulary team [Add the APR-DRG](https://github.com/OHDSI/Vocabulary-v5.0/issues/36) into Concept and change domain_id to 'Cost'.  Add the above note to the CDM Wiki FAQ.

**Comment by cgreich** [comment]
Wait. Didn't @dimshitc attempt a mapping, with varying domains?

**Comment by aostropolets** [comment]
correct. Still needs to be done.

**Comment by cgreich** [comment]
so, it's not done. Need to explain what the vocab team came up with.

**Comment by burrowse** [comment]
It would be great to have information on where this information is best stored.

 In the PEDSnet network, we have put this information in the `Observation` table, using an `observation_concept_id` of 3040464 (hospital discharge DRG) and populating the 'value_as_concept_id` field with the concept_id corresponding to the DRG code in the source.

DRGs are associated with conditions but are a part of the billing workflow. The DRG does not represent a $ figure but a standard way of reporting the diagnosis associated with a visit. In our network, we are not including billing and cost information, so we have not plugged it into the Cost table.

The DRG and MS-DRG vocabularies exist in the standard vocabulary. We would need the APR-DRG at some poing @cgreich and @dimshitc are aware.

**Comment by dimshitc** [comment]
DRGs should be stored in the COST table using the DRG_CONCEPT_ID and DRUG_SOURCE_VALUE columns, right?
so, no mapping to conditions (e.g. 38001518 Coagulation disorders) or procedures (38001508 Splenectomy w CC), right?

**Comment by vojtechhuser** [comment]
We should also consider non-USA and their DRGs (if applicable)

**Comment by MelaniePhilofsky** [comment]
Closing this issue. DRGs are in Athena and mapped to standard concept_ids.
