### ISSUE TITLE
Case to store the history of location change in Observation table

### ISSUE THREAD

**Issue by JaehyeongCho** [OHDSI/Themis#2]
I have [previously proposed ](http://forums.ohdsi.org/t/location-change/3837)to record a change in location on an observation table, but the proposal is not progressing. 

[This page](https://github.com/OHDSI/CommonDataModel/issues/91) discusses the update of the location table, but discusses the column of the location table rather than the discussion of the record of the location change.

I think that if the history of location is recorded in the observation table, it can generate more good evidence.

What do you think about recording the history of location changes in the Observation table?

**Comment by rtmill** [comment]
The GIS working group has proposed creating a location_history table for this purpose. 
Details here: [https://github.com/OHDSI/gis/wiki/Location-history](https://github.com/OHDSI/gis/wiki/Location-history)
