### ISSUE TITLE
Masking of Items Related to a Person

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#21]
TYPE | NOTES
-- | --
ITEM | Are there conditions/procedures/drugs or other items that should be masked/hidden in the CDM?
FORUM POST | http://forums.ohdsi.org/t/masking-of-data-about-a-person/4373
SOLUTION | The masking of information related to a person is dependent on the organization's privacy policies and may vary by data asset.
NEXT STEPS |  Work with CDM WG to add this statement  to FAQs.  <BR /><BR />**QUESTION** Are there conditions/procedures/drugs or other domains that should be masked/hidden in the CDM? <br/><br />**ANSWER** The masking of information related to a person is dependent on the organization's privacy policies and may vary by data asset.<BR/><BR/>https://github.com/OHDSI/CommonDataModel/wiki/Frequently-Asked-Questions

**Comment by PRijnbeek** [comment]
Will not apply for our database and I have not had this questions from datasources we are mapping in Europe so far, but i think it is a good suggestion to add to the FAQ
