### ISSUE TITLE
Source Concepts for Local Variables

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#22]
TYPE | NOTES
-- | --
ITEM | How should local source codes be managed?  Should I assign my own CONCEPT_IDs?  How have others handled this?
FORUM POST | http://forums.ohdsi.org/t/themis-question-what-do-people-put-in-the-source-value-fields/4092/
SOLUTION | There are three approaches to handle source codes that are not in the OMOP Vocabulary (in order of complexity):<br /> <br />1. **Leveraging the SOURCE_TO_CONCEPT_MAP:**  In the OMOP Vocabulary there is an empty table called the [SOURCE_TO_CONCEPT_MAP](https://github.com/OHDSI/CommonDataModel/wiki/SOURCE_TO_CONCEPT_MAP).  It is a simple table structure that allows you to establish mapping(s) for each source code with a standard concept in the OMOP Vocabulary (TARGET_CONCEPT_ID). This work can be facilitated by the OHDSI tool [USAGI](https://github.com/OHDSI/Usagi) which does text similarity between your source code descriptions and the OMOP Vocabulary and exports mappings in a SOURCE_TO_CONCEPT_MAP table structure.  Example SOURCE_TO_CONCEPT_MAP files can be found [here](https://github.com/OHDSI/ETL-CDMBuilder/tree/master/man/VOCABULARY_ADDITIONS).  These generated SOURCE_TO_CONCEPT_MAP files are then loaded into the OMOP Vocabulary's empty SOURCE_TO_CONCEPT_MAP prior to processing the native data into the CDM so that the CDM builder can use them in a build.<br /><br />2. **Adding CONCEPT.CONCEPT_IDs:** When an source code is not supported by the OMOP Vocabulary, one can create a new records in the CONCEPT table, however the CONCEPT_IDs should start >2000000000 so that it is easy to tell between the OMOP Vocabulary concepts and the site specific concepts. Once those concepts exist CONCEPT_RELATIONSHIPS can be generated to assign them to a standard terminologies, USAGI can facilitate this process as well.<br/><br/>  3. **Work with ODYSSEUS Data Services to add to OMOP Vocabulary:**  The OMOP Vocabulary is an evolving thing and new vocabularies can be added, however working with the ODYSSEUS team is the best way to manage performing this task.
NEXT STEPS |  Add this description with the CDM WG to the [FAQ section](https://github.com/OHDSI/CommonDataModel/wiki/Frequently-Asked-Questions).

**Comment by PRijnbeek** [comment]
We agree with the proposal and are testing out option 2 on our data at the moment

**Comment by ericaVoss** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/55c09522-48c7-4597-bf8d-63cd5f94649d-f9de47cd-e918-4b50-831d-d887a6386e5f-v1.png?transparent=1&palette=1&width=246)

**Comment by clairblacketer** [comment]
#teamSTCM

**Comment by alondhe** [comment]
My vote is for #3, but in the interim, I'd go with #1 (or, #teamSTCM). #2 should be in size 3 AND white font.

**Comment by PRijnbeek** [comment]
:) @alondhe if this is about preference we all want number 3 sure.

Number 2 just let’s me use all the tools and methods. I could run Achilles on my local coding system that is not yet in the vocab etc. Number 1 advantage for ETL step i see as well but does not allow me to use the tools.  

Disadvantage of number 2 could be that others touch the vocabulary and may introduce errors.
