### ISSUE TITLE
Quantities of 0 for Devices and Procedures

### ISSUE THREAD

**Issue by MeghanPettine** [OHDSI/Themis#26]
TYPE | NOTES
-- | --
ITEM | How should we handle   quantities of ‘0’ in Devices and Procedures?
FORUM POST | http://forums.ohdsi.org/t/quantities-of-0-for-devices-and-procedures/4614
SOLUTION | Default quantities of ‘0’ to ‘1’. If there is a record in the source then we can assume this occurred at least once. 
NEXT STEPS | Update the PROCEDURE_OCCURRENCE and DEVICE WIKI pages under conventions.

**Comment by clairblacketer** [comment]
Update to say "in absence of units"  - this is in relation to blood transfusion and the addition of unit_concept_id to device_exposure

**Comment by ericaVoss** [comment]
Discussion around this issue in THEMIS meeting at the OHDSI 2022.  We need to be clearer.

**Comment by dimshitc** [comment]
procedure_occurrence.quanity
fix note about turning 0 of procedure quanity to "when NULL or 0" and 
 add "do this if you're confident that procedure occurred, do the investigation if needed"

**Comment by Alexdavv** [comment]
It could be questionable if  "0" quantity in the source always means that the procedure was performed, or if it was used as a flag of the canceling of the order. I'd recommend adding 2 short comments about:
- the source has to be investigated on it;
- follow the general rule that events that were not performed should not be captured in the CDM.

**Comment by MelaniePhilofsky** [comment]
CDM conventions have been updated.
