### ISSUE TITLE
Standardization of Measurements and Units

### ISSUE THREAD

**Issue by MeghanPettine** [OHDSI/Themis#28]
see SOLUTION in a related issue here: https://github.com/OHDSI/Themis/issues/4

TYPE | NOTES
-- | --
ITEM | Standardization of Measurements and Units
FORUM POST | http://forums.ohdsi.org/t/themis-subgroup-measurement-procedure/3675
SOLUTION | see below 
NEXT STEPS | modify convention for MEASUREMENT 

SOLUTION: modify current conventions slightly.

**Comment by chandryou** [comment]
@ericaVoss  @MeghanPettine  @vojtechhuser 
We're making the standard measurement_concept_id set and operator_concept_id, unit_concept_id, examples of the values for each measurement_concept_id for Korean hospitals.

Now we're ready to release top 100 standard measurement concept_id and example set for Korea. 
Should we release this in this github repository? This measurement concept will help others to map their measurement vocabulary with OMOP vocabulary and ultimately standardize the measurement across OHDSI network.

**Comment by vojtechhuser** [comment]
Several updates are:
- the network study to collect data from sites is here https://github.com/OHDSI/StudyProtocolSandbox/blob/master/themis/extras/notes.md
- AMIA poster exists and a draft manuscript to JAMIA Open
- final results that are currently being implemented into Achilles are here: https://github.com/OHDSI/StudyProtocolSandbox/blob/master/themis/extras/results/S3-units-with-tests.csv
- I emailed with Chan about Korean reference set and he planned to upload it to https://github.com/OHDSI/StudyProtocolSandbox/blob/master/themis/extras/ next to the other reference set (eg., LOINC top 2000)

**Comment by PRijnbeek** [comment]
We agree with the proposal

**Comment by clairblacketer** [comment]
It seems like more work needs to be done on this one so I will not be incorporating any related changes into CDM v6.0 or documentation.

**Comment by vojtechhuser** [comment]
See solution proposed here: https://github.com/OHDSI/Themis/issues/4

**Comment by vojtechhuser** [comment]
This is included in #4 so closing this issue.
