### ISSUE TITLE
Observation – Family History of 

### ISSUE THREAD

**Issue by MeghanPettine** [OHDSI/Themis#29]
TYPE | NOTES
-- | --
ITEM | Observation – Family History of 
FORUM POST | http://forums.ohdsi.org/t/how-to-represent-family-history/3386
SOLUTION | We want to recommend that all family history get the OBSERVATION_CONCEPT_ID = 4210989 - Family history with explicit context and then if there is an associated condition it should get put into the VALUE_AS_CONCEPT_ID. For example, if I get this ICD9 V17.5-Family history of asthma, the Vocab would map it to 4210989 but there would also be a separate non-standard relationship to asthma.  Any time I have a code mapped to 4210989 then I will do a separate query to get to its associated condition.
NEXT STEPS | Add as a convention under the [OBSERVATION](https://github.com/OHDSI/CommonDataModel/wiki/OBSERVATION) page.<br />There is no connection from the disease to the "family history of". Check that all relationships exist. If they do not, then talk to SNOMED. Next step is to add SNOMED extension

**Comment by schuemie** [comment]
Could someone explain the rationale for this solution? 

I can think of two reasons why we'd instead always want to use 4210989:

1. Consistency for all family history. As an application developer, that would make my life a lot easier. I can pull all family history in with one query.

2. Explicit link between the disease concept and the family history.

**Comment by aostropolets** [comment]
@schuemie   we basically used the same logic when creating this approach. On the other hand, we still want to keep precoordinated SNOMED concepts for two main reasons:
1. When we break down source concepts it occurs as a quite time-consuming task. Not all are prepared to that, especially taking into account that this time can be allocated to more important and clinically relevant mappings.
2. Usagi will map source concepts to the direct SNOMED counterparts, which will be useless and will need manual review; this again leads us to the first paragraph.

**Comment by ericaVoss** [comment]
Moving this conversation to the Wiki:
http://forums.ohdsi.org/t/how-to-represent-family-history/3386/7

**Comment by aostropolets** [comment]
I don't think that ICD9CM has been reviewed recently, so it will probably be done as a part of this review. Thanks for the reminder!

**Comment by dimshitc** [comment]
Yeah, right now it's mapped to Family history 
and maps to value to "Asthma".
Is it the final decision?
"If we have a matching concept in SNOMED, then use the respective observation_ concept_id. If we do NOT have a matching SNOMED code, then observation_concept_id should be ‘4210989 Family history with explicit context’ and value_as_concept_id should be the related procedure, condition etc."

**Comment by aostropolets** [comment]
It is the final decision

**Comment by dimshitc** [comment]
Good, thanks @aostropolets.
We'll change this

**Comment by dimshitc** [comment]
ICD10 mappings are already done in this way:

> "If we have a matching concept in SNOMED, then use the respective observation_ concept_id. If we do NOT have a matching SNOMED code, then observation_concept_id should be ‘4210989 Family history with explicit context’ and value_as_concept_id should be the related procedure, condition etc."

Waiting for release, just day or two.

ICD10CM and ICD9CM are in still the backlog.
The update takes time as we updating not only the links mentioned above, but reviewing the whole corpus of manual mappings

**Comment by vojtechhuser** [comment]
Can someone summarize the final design with an example from ICD9CM and ICD10CM?

**Comment by vojtechhuser** [comment]
V17.5 is a interesting - asthma hx became bicycle  injury

![image](https://user-images.githubusercontent.com/7526119/57403201-1c501c00-71a7-11e9-8b8b-3837f8f6f978.png)

**Comment by p-talapova** [comment]
@vojtechhuser please, look at the diagram below to see the final mapping design of ICD concepts indicating a history: 
![ICD History mapping](https://user-images.githubusercontent.com/42737398/57862738-8731d080-7801-11e9-8f75-6dfe93564ab6.jpg)

Examples:
![image](https://user-images.githubusercontent.com/42737398/57863893-8e59de00-7803-11e9-97db-62514a97c0d0.png)

At the present time, we are implementing such a model toward all history-related ICD concepts to increase the number of equivalent mappings.
The current state is the following:
![History example 2](https://user-images.githubusercontent.com/42737398/57865717-c7e01880-7806-11e9-8623-cac6c8e99dd0.PNG)

**Comment by chandryou** [comment]
It seems that we did have the final decision for this problem
"If we have a matching concept in SNOMED, then use the respective observation_ concept_id. If we do NOT have a matching SNOMED code, then observation_concept_id should be ‘4210989 Family history with explicit context’ and value_as_concept_id should be the related procedure, condition etc."

Is there anyone teach me why this issue is open now?

**Comment by cgreich** [comment]
@chandryou:

Not a good decision, but unless we fix the vocabulary and get SNOMED on board I am afraid that's what it is. Will bring it up with them as one of the issues.

**Comment by MelaniePhilofsky** [comment]
Closing issue. Vocabulary has been updated.
