### ISSUE TITLE
Device:  Default Quantity when the quantity is not provided or 0

### ISSUE THREAD

**Issue by mvanzandt** [OHDSI/Themis#3]
TYPE | NOTES
------- | ------
ITEM | What should happen to the quantity when the record is moved over to the OMOP CDM if the quantity from the source is either not provided or set to 0?
FORUM POST | - 
SOLUTION | Default quantities of ‘0’ to ‘1’, if there is a record in the source then we can assume that this happened at least once.
NEXT STEPS | Update the CDM Wiki on DEVICE_EXPOSURE.quantity column Description.  Post issue to ACHILLES GitHub requesting this rule be added

**Comment by ericaVoss** [comment]
Duplicate with #26
