### ISSUE TITLE
Glean month if birth absent e.g. from Observation Period starting same year

### ISSUE THREAD

**Issue by tomgalia** [OHDSI/Themis#30]
Type | Notes
------------ | -------------
Item| Glean month if birth absent e.g. from Observation Period starting same year
Forum Post | http://forums.ohdsi.org/t/eliminating-persons-themis-wg3-topic-2/3974
Solution | If we do not know the month or day of birth, we do not guess.  A person can exist without a month or day of birth.  If a person lacks a birth year we will drop that person.
Next Steps | To add this as a convention under the PERSON wiki page.

**Comment by PRijnbeek** [comment]
Agreed. I do know multiple databases that use day 15 for all patients or as default for missing.

I could imagine they like to use the same approach in source and cdm version.

**Comment by PRijnbeek** [comment]
Yes i agree with the convention, just saying since age is a crucial  value for comparing and study between source and cdm some may not follow the convention to allow that.

**Comment by PRijnbeek** [comment]
But to your point they could indeed do that in analytical step if we explain that.
