### ISSUE TITLE
Masking of person’s age based on privacy regulations

### ISSUE THREAD

**Issue by tomgalia** [OHDSI/Themis#31]
Type | Notes
------------ | -------------
Item | Masking of person’s age based on privacy regulations
Forum Post | 
Solution |  Depends on the business, may need to mask these ages,  if over 110-115 y.o --> drop <br> Apply business rule.  Save rules in metadata table.  Always meet HIPAA standards.
Next Steps |  Accepted by the THEMIS F2F meeting.

**Comment by ericaVoss** [comment]
Closing for ticket #21
