### ISSUE TITLE
Gender Identification vs. Biological Sex

### ISSUE THREAD

**Issue by tomgalia** [OHDSI/Themis#32]
Type | Notes
------------ | -------------
Item | Gender Identification vs. Biological Sex
Forum Post | http://forums.ohdsi.org/t/should-transgenders-be-excluded-from-the-cdm/2750
Solution | The PERSON.GENDER_CONCEPT_ID should store what is believed to be the biological or sex assigned at birth.  If the data set does have gender identification information, this should be stored in the OBSERVATION table (using the gender concepts 8532-Female or 8507-Male in OBSERVATION_CONCEPT_ID).
Next Steps | Add this under conversions under PERSON wiki.

**Comment by PRijnbeek** [comment]
Agreed, however is this not in contradiction with the multiple gender proposal?
