### ISSUE TITLE
Person without no transaction records besides observation_period/payer plan period. Keep if no other record in other data (Typically claims data)

### ISSUE THREAD

**Issue by tomgalia** [OHDSI/Themis#35]
Type | Notes
------------ | -------------
Item | Person without no transaction records besides observation_period/payer plan period. Keep if no other record in other data (Typically claims data)
Forum Post | http://forums.ohdsi.org/t/eliminating-persons-themis-wg3-topic-2/3974
Solution | Keep Person Record.  (useful for claims data: enrollees vs. active patients)
Next Steps | Accepted by the THEMIS F2F meeting.

**Comment by ericaVoss** [comment]
Duplicate of #9
