### ISSUE TITLE
Primary provider unknown

### ISSUE THREAD

**Issue by tomgalia** [OHDSI/Themis#36]
Type | Notes
------------ | -------------
Item | Primary provider unknown for a person.
Forum Post | http://forums.ohdsi.org/t/unknown-persons-primary-provider/4549
Solution | When the primary provider is unknown for a person then leave the PROVIDER_ID blank.
Next Steps | In the CDM Wiki, under the PERSON page, under conventions add this text.

**Comment by PRijnbeek** [comment]
We agree, but that field is not mandatory now in the person table. Are we adding a comment for each field that is not mandatory?

**Comment by cgreich** [comment]
That should not be the case. Will be nullable.

**Comment by clairblacketer** [comment]
@PRijnbeek @cgreich the PROVIDER_ID field in the PERSON table is currently not required and I agree with @PRijnbeek that this makes the above solution implied.
