### ISSUE TITLE
Mother to baby and father to baby link - specify which concept to use 

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Themis#38]
ITEM: see title
FORUM POST:  see below
SOLUTION: 
_only convention for mother, father is the main scope of this themis proposal. First two conventions. One additional convention tries to guide (to as specifically) other biological relationships._

* use concept 4277283 to represent personA is biological mother of personB (in column relationship_concept_id). Use concept 4321888 to represent personC is biological father of personB. Prioritize mother or father relationship (if known) and try to avoid only saying biological parent. Only if parent gender is not known, use 'biological parent' (concept 4029630). Use of biological parent (and not mother or father) triggers a heel data quality notification).
* If person A has a recorded biological relationship to person person B (e.g., mother, father, parent), always represent the reverse relationship as well (daughter, son, child). Prioritize biological son (4014096) /biological daughter (4308126)  based on sex at birth. Only if child gender is not know, use biological child (4326600). Lack of reverse relationship triggers data quality error. Use of less preferred 'biological child' concept triggers data quality notification.

* If you have other _biological_ relationship in source data, use concepts that are descendants of concept_id 4054070 (relative). This convention does not prevent representing other non-biological relationships between persons. The goal of this convention is to restrict the value set of concepts for "encouraged" biological relationships. _(heel notification not possible here; no way to distinguish it is biological statement)_

_see concept_ids discussion below. In your comment, indicate concepts you like the most_

NEXT STEPS: add conventions in SOLUTION

HEEL: DQ notification if parent concept id is used (not mother or father)

----------------------------

Current specs do not prescribe specific vocabulary concept to use when linking persons in FACT_RELATIONSHIP

Goal: recommend specific concept for column **relationship_concept_id**.

Use natural father and natural mother from this parent concept of natural parent
http://athena.ohdsi.org/search-terms/terms/4029630

(reverse relationship is natural child)
http://athena.ohdsi.org/search-terms/terms/4326600

------------------------------
links to forum
http://forums.ohdsi.org/t/voijtechs-question-conventions-for-iological-relationships-in-fact-relationship-table/158

http://forums.ohdsi.org/t/mother-father-and-baby-link/1044

The gap in specs is here
https://github.com/OHDSI/CommonDataModel/wiki/FACT_RELATIONSHIP#conventions

I want to write a Data Quality notification in Achilles but for that it needs to tighter specified.

**Comment by vojtechhuser** [comment]
Discussed briefly in WG-1 today. Will add snomed codes to the propsal. 

biological father verified by DNA vs. father by self proclamation - was discussed and thought to be overengineering it.

**Comment by vojtechhuser** [comment]
I updated the issue with 2 specific codes to use for mother and father

**Comment by alondhe** [comment]
Hi @vojtechhuser -- in the [MotherChildLinkage package](https://github.com/alondhe/MotherChildLinkage) which we use at Janssen, we utilize the following query to populate the results into the fact_relationship table:

```
select
    56 as domain_concept_id_1, 
    mom_person_id as fact_id_1, 
    56 as domain_concept_id_2, 
    baby_person_id as fact_id_2, 
    40478925 as relationship_concept_id
  from #probables
  union 
  select 
    56 as domain_concept_id_1, 
    baby_person_id as fact_id_1, 
    56 as domain_concept_id_2, 
    mom_person_id as fact_id_2, 
    40485452 as relationship_concept_id
  from #probables

```

For mother-child linkages, the above query will use "Person" as the domain concept Id, "Mother of subject" as the relationship concept Id for the moms, "Child of subject" for the kids. We haven't developed father-child linkages yet, but I imagine the SNOMED concept 40478917 ("Father of subject") would be the concept for dads.

**Comment by vojtechhuser** [comment]
http://athena.ohdsi.org/search-terms/terms/40478925
http://athena.ohdsi.org/search-terms/terms/40485452

**Comment by vojtechhuser** [comment]
I am making a comment to US ISA to point to this.

**Comment by vojtechhuser** [comment]
first post was edited to have clearer solution text

**Comment by vojtechhuser** [comment]
discussed. and advanced to next stage.

**Comment by vojtechhuser** [comment]
no alterations were raised by the community.  Can we decide step 8A or 8B.

**Comment by vojtechhuser** [comment]
![image](https://user-images.githubusercontent.com/7526119/59279268-a6215800-8c31-11e9-9a6d-4695d48d19b0.png)

**Comment by MelaniePhilofsky** [comment]
Closing this issue. It is now with the Vocabulary team.
