### ISSUE TITLE
Event type concept when vocabulary maps to a different domain

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Themis#40]
Type | Notes
------------ | -------------
ITEM|The medical event (condition, procedure, ...) type should be determined independent of the target domain.  For example, if a procedure code in the facility header record is mapped to an observation, the event type should be concept id 42865905, Facility Header, where the domain is 'Type Concept' and the vocabulary id is 'Procedure Type', even though the event will reside in Observation.
FORUM POST | http://forums.ohdsi.org/t/how-to-determine-event-type-concept-when-vocabulary-maps-to-a-different-domain/5955/15
SOLUTION| Themis convention that the event type is determined by the source of the data without regard to the target domain of the source code and that any concept in the 'Type Concept' domain is a valid event type concept regardless of the table the event resides in.
NEXT STEPS|Create a forum post for discussion.

**Comment by don-torok** [comment]
**TYPE** |** NOTES**
-------|-----------------------------------------------------------------------------------
ITEM|The medical event (condition, procedure, ...) type should be determined independent of the target domain.  For example, if a procedure code in the facility header record is mapped to an observation, the event type should be concept id 42865905, Facility Header, where the domain is 'Type Concept' and the vocabulary id is 'Procedure Type', even though the event will reside in Observation.
FORUM POST | None
SOLUTION| Themis convention that the event type is determined by the source of the data without regard to the target domain of the source code and that any concept in the 'Type Concept' domain is a valid event type concept regardless of the table the event resides in.
NEXT STEPS|Create a forum post for discussion

**Comment by MelaniePhilofsky** [comment]
Where are we with this? Has it been ratified? If not, this is a +1. We have some immunization data that we know comes from multiple sources (state registry, administered, patient reported, etc.). However, we do not have the data that distinguishes where each individual record came from. And there isn’t a generic “from EHR record” in the concept table with vocabulary_id = 'drug type'

**Comment by don-torok** [comment]
@MelaniePhilofsky there is a form post for this topic, which I just added to above note:
http://forums.ohdsi.org/t/how-to-determine-event-type-concept-when-vocabulary-maps-to-a-different-domain/5955/15
I would re-ask the question there and I will comment there so that others will see.

**Comment by cgreich** [comment]
The proposal for this is here: https://forums.ohdsi.org/t/concept-type-consolidation-please-take-a-look/8306.

**Comment by MelaniePhilofsky** [comment]
Closing this issue. The Vocabulary and conventions have been updated.
