### ISSUE TITLE
Multiple Provider Specialities

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Themis#43]
TYPE | NOTES
-- | --
ITEM | How do we handle providers with multiple specialties? 
FORUM POST | http://forums.ohdsi.org/t/new-comprehensive-hierarchy-for-providers-visits-and-place-of-service-specialty-care-site/5633
SOLUTION | Currently there is a convention: <br> `A single Provider cannot be listed twice (be duplicated) in the table. If a Provider has more than one Specialty, the main or most often exerted specialty should be recorded.`
NEXT STEPS | Understand from @cgreich how this should be working given what is now in the Vocabulary.  Supposedly there is a hierarchy now.

**Comment by cgreich** [comment]
And how do we know if two records are the same guy?

**Comment by clairblacketer** [comment]
Same NPI or SOURCE_PROVIDER_ID?

**Comment by cgreich** [comment]
Ugly. We have the same NPI, but a different provider_id? Half of the folks will get confused.

**Comment by cgreich** [comment]
Friends:

Here is what I will do. I will pull the list of these multiple-specialty docs and check it against the specialty hierarchy we are building. Because in the real world there are almost no true double-specialty docs. Trust me. It takes a lot of time, and a lot of training, and a lot of examinations, a lot of lost income to get there. What's happening a lot is like a "cardiologist" will also call himself "internist" in another circumstance. But of course cardiology is a subspecialty of internal medicine.

I will report back how bad the situation really is.

**Comment by stephanieshong** [comment]
a provider with a NPI number can be a care_site, a hospital, with multiple specialty associated with it. (i.e. outpatient specialty clinic,  hospital and a hospice.) 
a provider as a physician who took care of a patient can be medpeds in US, who is both internal medicine and pediatric specialty. 
Not being able to add specialty value associated with the same NPI is causing a problem both in  provider and the care_site table.

**Comment by cgreich** [comment]
@stephanieshong: 

- NPI: That is correct. In the CDM, we only collect Entity Type 1 providers: Individuals, including sole proprietors. And, to be honest, I think even that is TMI.
- Specialty of organizations: We do not model those. We had debates about that. [It wouldn't work](https://forums.ohdsi.org/t/new-comprehensive-hierarchy-for-providers-visits-and-place-of-service-specialty-care-site/5633).
- Medical pediatrics: No problem adding that as a concept, as descendant of both [Pediatric Medicine](https://athena.ohdsi.org/search-terms/terms/38004477) and [Internal Medicine](https://athena.ohdsi.org/search-terms/terms/38004456). Strangely, there is no such thing, even though we have tons of mixed pediatric specialties (look under "[Subsumes](https://athena.ohdsi.org/search-terms/terms/38004477)").

**Comment by MelaniePhilofsky** [comment]
Closing this issue. Vocabulary and CDM conventions were updated.
