### ISSUE TITLE
Non-Individuals in the Provider Table

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#45]
TYPE | NOTES
-- | --
ITEM | Currently there is a PROVIDER convention 2:  "Many sources do not make a distinction between individual and institutional providers. The PROVIDER table contains the individual providers."  But this needs to be clearer defined for institutions (especially since GENDER is required).
FORUM POST | http://forums.ohdsi.org/t/non-individuals-in-the-provider-table-themis/5720
SOLUTION | Update conventions on the provider table.
NEXT STEPS | Update the Convention 2 PROVIDER `Many sources do not make a distinction between individual medical groups and institutional providers. The PROVIDER table contains the individual providers.`<br><br> Add the following convention `In cases where a provider has unknown gender or may be a individual medical group set GENDER_CONCEPT_ID = 0.`

**Comment by vojtechhuser** [comment]
Agree with the idea. Can you describe more about the sources that don't. And how is it outside USA.

It is interesting that gender is required. I would almost make it optional.

**Comment by cgreich** [comment]
You look it up in the vocabulary, and it will tell you if it is a Visit or Provider concept.

**Comment by MelaniePhilofsky** [comment]
CDM conventions were updated.
