### ISSUE TITLE
Place_of_Service_concept_id - Clean up, make international - Currently CMS US based

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#47]
TYPE | NOTES
-- | --
ITEM | 
FORUM POST | http://forums.ohdsi.org/t/visit-vs-place-of-service/4006 br> <br> http://forums.ohdsi.org/t/new-comprehensive-hierarchy-for-providers-visits-and-place-of-service-specialty-care-site/5633
SOLUTION | 
NEXT STEPS | Christian to discuss at next THEMIS call

**Comment by vojtechhuser** [comment]
Please populate the solution row in the top table.

**Comment by cgreich** [comment]
Use [this](http://forums.ohdsi.org/t/new-comprehensive-hierarchy-for-providers-visits-and-place-of-service-specialty-care-site/5633/43), @clairblacketer. I can't edit this thing, here.

**Comment by MelaniePhilofsky** [comment]
Closing this issue. CDM conventions & Vocabulary updated.
