### ISSUE TITLE
Multiple Addresses per Provider

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#48]
TYPE | NOTES
-- | --
ITEM | Example: Doctor comes to hospital. Bill shows his office address but place of service is hospital.  Billing address different from actual site where patient was. <br><br>Owner: Ron Stewart<br><br>Proposal: Handled in visit-detail 5.3 table.  <br><br> https://github.com/OHDSI/CommonDataModel/issues/153 <br><br>Clair: Location history table can handle multiple addresses for same location ID. Provider in multiple care sites are assigned different provider IDs. ADDRESSED. <br><br>Cs 03 AND 04: Require deeper nuanced discussion on how to handle, but not a priority now. Bring up in a discussion when Ron is present. Tom: Well discussed, make a priority. Follow up with Ron
FORUM POST | http://forums.ohdsi.org/t/multiple-addresses-per-provider-provider-address-differs-from-care-site/5653
SOLUTION | The CDM allows us to capture location of visits, so knowing where a patient was treated is quantified in the CDM. If a provider has multiple addresses the ETL should just choose one as it is unknown what the analytical use case for storing multiple addresses per provider. <br><br>The question of how to handle a situation where the billing address differs from where the patient received care is already handled in the CDM. The VISIT_OCCURRENCE table has a separate PROVIDER_ID and CARE_SITE_ID for expressly this purpose. This is already handled with Convention 8 on the VISIT_OCCURRENCE page (https://github.com/OHDSI/CommonDataModel/wiki/VISIT_OCCURRENCE).
NEXT STEPS | Update [Convention #3 under PROVIDER](https://github.com/OHDSI/CommonDataModel/wiki/PROVIDER).<br>A single Provider cannot be listed twice (be duplicated) in the table. In situations where a provider has multiple addresses the ETL should choose the best one. If a Provider has more than one Specialty, the main or most often exerted specialty should be recorded.<br><br>Update [Conventions #8 under VISIT_OCCURRENCE](https://github.com/OHDSI/CommonDataModel/wiki/VISIT_OCCURRENCE):<br>One visit may involve multiple care sites, in which case the ETL must specify how a single CARE_SITE_ID is selected or leave the CARE_SITE_ID field null. When the address of the provider and site of care differ you can use the CARE_SITE_ID to capture location of care and PROVIDER_ID to capture provider office.

**Comment by MelaniePhilofsky** [comment]
Closing this issue. Conventions updated.
