### ISSUE TITLE
Specialty & Add Clinical Title

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#49]
TYPE | NOTES
-- | --
ITEM | Provider specialty not well captured in the Vocabulary.  
FORUM POST | http://forums.ohdsi.org/t/provider-specialty-code-set-clean-up/3888 <br> <br> http://forums.ohdsi.org/t/care-sites-and-specialty-specialty-code-clean-up/4538/4<br> <br> http://forums.ohdsi.org/t/new-comprehensive-hierarchy-for-providers-visits-and-place-of-service-specialty-care-site/5633
SOLUTION | Incorporate NUCC, ABMS, HES Specialty, and Specialty-CMS.  The order of preference should be OMOP->Specialty->Place of Service->NUCC->ABMS->HES Specialty->UB04
NEXT STEPS | Ultimately the Vocabulary team will work on.  Double check this has been implemented in the Vocabulary.  Maybe we need to remove duplicates.

**Comment by MelaniePhilofsky** [comment]
Closing this issue. Vocabulary was updated.
