### ISSUE TITLE
Multiple deaths on the same day

### ISSUE THREAD

**Issue by aostropolets** [OHDSI/Themis#5]
TYPE | NOTES
-- | --
ITEM | How should we handle multiple deaths on the same day?
FORUM POST | http://forums.ohdsi.org/t/multiple-cause-of-death/4551
SOLUTION | If multiple death records occur, the date and the person have to be the same, but the cause can be different. Can be reported by different sources as well.
NEXT STEPS | Update the CDM Wiki on DEATH.cause_concept_id column description.

**Comment by vojtechhuser** [comment]
Future conventions should come with Heel rule suggestion. In this case error is issued when group_by person_id gives to 2 or more dates.
