### ISSUE TITLE
Single Person Record

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#50]
I don't think we mention anywhere on the WIKI that there is only supposed to be one PERSON record per person.

https://github.com/OHDSI/CommonDataModel/wiki/PERSON

**Comment by cgreich** [comment]
We don't? How would you understand the first sentence: "The Person Domain contains records that uniquely identify each patient..." ?

**Comment by vojtechhuser** [comment]
so let's close it.
