### ISSUE TITLE
Visit discharge to.

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Themis#52]
Current documentation limits discharge to concept_id to 'Place of Service' vocabulary however, there is a set of concepts that belong to vocabulary 'UB04 Pt dis status' that may better describe the discharge disposition.

**Comment by vojtechhuser** [comment]
makes some sense. If you provide example of at least on UB04 concepts that would help the group

**Comment by MelaniePhilofsky** [comment]
Closing this issue. Vocabulary has been updated.
