### ISSUE TITLE
unit_source_concept_id in MEASUREMENT

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Themis#53]
PROBLEM: original data can not be stored fully

FORUM: see forum link here https://github.com/OHDSI/CommonDataModel/issues/259 

SOLUTION:
add new column to CDM  unit_source_concept_id  (optional) this is representation of unit_source_value as concept_id
(data type as all other CIDs, optional)

**Comment by MelaniePhilofsky** [comment]
Closing this issue. CDM v5.4 contains this field.
