### ISSUE TITLE
What to do with Payer Plan Period for EHR where Person defined, but no medical records

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Themis#54]
Some EHR systems may have patient lists which they want to retain even if the system has no additional data on the person.  Convention for the payer plan period has been to set the start and end dates  as the first to correspond to the dates of the person first and last interaction.  It is probably time to say that a payer plan record is NOT required if there is no insurance information for a person. (This was brought up at May 2019 Themis face to face)

**Comment by MelaniePhilofsky** [comment]
Closing this issue. Conventions have been updated. PPP is not a required table.
