### ISSUE TITLE
Revisit issue #10 on DateTime

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Themis#55]
At the May 2019 Themis face to face some requested that we review the rule for determining the time of date time fields when time is not known. Current rule is 'Choose default time of 00:00:00 if time is unknown. If you do have time and receive a time of 00:00:00 just shift 1 second to 00:00:01'.  This seems to add complexity for the rare occasions when the system has exact time, but the time happens to be 00:00:00.  Suggest the rule be changed to say 'if your source only has date information default the time to 00:00:00', and not worry about the possibility that a source system with time information has an event that starts at 00:00:00.

**Comment by MelaniePhilofsky** [comment]
Closing this issue. Datetime fields are NOT mandatory in CDM v5.4 and the conventions reflect this.
