### ISSUE TITLE
How to determine Drug Exposure End Date

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Themis#57]
Drug end date become mandatory in CDMv6.  Conventions on how to determine end date 
1. If mail order assume 90 days supply
2. If from a procedure assume a single day
3. If days supply defined set end date to start + days supply - 1
4. If no information, but it is a prescription assume 30 days supply

**Comment by schillil** [comment]
I'm assuming the above is for prescription data. How are is the refill information be handled. I write/send mail order scripts for 90 day plus 3 refills - so for 360 days, so it seems it should be 360 days or a discontinue date, which ever is earlier.

**Comment by cgreich** [comment]
Good point, @schillil. For pharmacy dispensing data each refill is recorded. But for prescription data you declare the prescription and all refills in one go. So, somebody ETLing those data should add refills with @don-torok's rules above.

**Comment by don-torok** [comment]
Be careful because this gets into a potential difference in the definition of refills in source data.  The number of allowable refills for a script vs the number of possible refills this entry represents.  I am not sure which of these two definitions apply to drug_exposure.refills.  I argue for the first, but current description is implies the second.

**Comment by MelaniePhilofsky** [comment]
Closing this issue. Conventions have been updated.
