### ISSUE TITLE
How to replace the concept_id no.8552 in race_concept_id of Person Table

### ISSUE THREAD

**Issue by song-eu** [OHDSI/Themis#60]
Type: Person
Problem: In the current CDM platform in Korea, Race_concept_id is just classified as 'Native' and 'Foreigner'.
‘Foreigner’ is identified using the Unknown code (concept id#8552). 
But, we noticed that the Unknown code is expired.
In Athena, there is concept id#45431577 of RACE:Unknown in the 'Race' domain.
Can the expired Unknown code(no. 8552) be replaced by concept id no.45431577? 
If not, with which code should the expired code be replaced?

**Comment by cgreich** [comment]
Will create a renewed ethnicity/race Domain soon, @song-eu. The ethnicity should be Korean or whatever else it is. "Unknown" will not be there, and neither "Foreigner". The latter is useless. We all are foreigners almost everywhere. You may as well have "Human".
