### ISSUE TITLE
Determining "quantity" in "PROCEDURE_OCCURRENCE" table

### ISSUE THREAD

**Issue by dianakim44** [OHDSI/Themis#62]
Question)
To determine "quantity" in "PROCEDURE_OCCURRENCE" table, 

What values should be written in procedure, surgery, measurement, examination, treatment and etc?

**Comment by don-torok** [comment]
You might get a better response if you post this in the CDM Builders forum and your question was more specific.

**Comment by MelaniePhilofsky** [comment]
Closing this issue. Conventions have been updated to reflect guidance.
