### ISSUE TITLE
[2022 US Symposium] Episode and Episode Event Tables Documentation

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#66]
TYPE | NOTES
-- | --
ITEM | Defining conventions for the Episode and Episode Event tables in the CDM v5.4 documentation.
FORUM POST | https://forums.ohdsi.org/t/2022-us-symposium-66-episode-and-episode-event-tables-documentation/17501
SOLUTION | TBD
NEXT STEPS | TBD

**Comment by MelaniePhilofsky** [comment]
@ericaVoss Where are we at with this issue?

**Comment by MelaniePhilofsky** [comment]
The documentation has been updated by the Oncology WG. I am closing this issue.
