### ISSUE TITLE
[2022 US Symposium] "history of"

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#68]
TYPE | NOTES
-- | --
ITEM | What to do with “history of”?  Family history of, prior medical history, prior surgical history, 
FORUM POST | https://forums.ohdsi.org/t/2022-us-symposium-67-history-of/17503
SOLUTION | TBD
NEXT STEPS | TBD

**Comment by marcel1334** [comment]
This post is based on the OHDSI Symposium 2022 Workshop discussion. Thanks to the workshop members, and special thanks to Eduard Korchmar.


In general we prefer generic appraoches so we can also write generic algorithms on this. Below the proposal for the "Family history of...", but for "History of..." we suggest the same approach:

1. Destandardize entire subhierarchy of "Familial history of clinical finding"(FHO), except for the root node and top nodes of branches pertaining to specific family members (mother, uncle, paternal grandmother etc)
2. Map all destandardized concepts to closest remaining standard hierarchy parent, with "Associated finding" attribute getting "Maps to value" treatment. Fully Defined concepts should be processed automatically. Primitive concepts in the hierarchy (78 in total) can be processed manually and mapped upwards with minimal loss of data, as it is established practice.
3. Convention should be published for generic approach to mapping: using either generic FHO or it's child with a specified relative for standard in OBSERVATION_OCCURENCE table entry, with value-as-concept_id being exact Condition.
4. Future compatibility support remains a task of the Vocabulary team.

**Comment by MelaniePhilofsky** [comment]
**Two issues here:** "history of" solved by Vocab and requires _CDM convention documentation_; "family history" needs discussion move to #29
