### ISSUE TITLE
[2022 US Symposium] ETL convention for DRUG_ERA/DRUG_EXPOSURE 

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Themis#70]
TYPE | NOTES
-- | --
ITEM | Develop user guidance or ETL convention for DRUG_ERA/DRUG_EXPOSURE count.
FORUM POST | https://forums.ohdsi.org/t/2022-us-sympoisum-70-etl-convention-for-drug-era-drug-exposure/17505
SOLUTION | TBD
NEXT STEPS | TBD

**Comment by Alexdavv** [comment]
An issue around the pack_content table.
https://github.com/OHDSI/Athena/issues/256#issuecomment-1132749981

**Comment by MelaniePhilofsky** [comment]
<!DOCTYPE html>

TYPE | NOTES
-- | --
ITEM | Develop user guidance or ETL convention for DRUG_ERA/DRUG_EXPOSURE count.
FORUM POST | https://forums.ohdsi.org/t/2022-us-sympoisum-70-etl-convention-for-drug-era-drug-exposure/17505
SOLUTION | We recommend add the following summary text to the ETL convention "The count of grouped DRUG_EXPOSURE records that were included in the DRUG_ERA row".
NEXT STEPS | Open a CDM GitHub issue so the documentation can be added to the User Guide section of the drug_era.drug_expsoure_count field.

**Comment by MelaniePhilofsky** [comment]
Closing this issue. It is in the hands of the [CDM WG](https://github.com/OHDSI/CommonDataModel/issues/546).
