### ISSUE TITLE
Migrate CDM from Gender to genetic Sex

### ISSUE THREAD

**Issue by clarkevans** [OHDSI/Themis#74]
The term "gender" is used in the CDM as a synonym for sex assigned at birth. This is confusing that the word gender was used and continues to be used, as gender is a social construct.  Moreover, a more useful meaning is genetic sex, where by the value "intrasex" should also be valid. This proposal proposes a 4-phase change to migrate to "genetic sex".

1. In the 5.X series, sex_concept_id would be added, along with a Sex domain with values (male, female, intrasex).
2. Applications could start using "Sex" for screens, making sure that Intrasex is a valid option besides Male and Female.
3. In the 6.X series, gender_concept_id and related columns could be removed.
4. Gender can then become an observation with possible values that more closely match social constructs.

This is a long-standing problem with the CDM.  It's time it gets addressed.

**Comment by MelaniePhilofsky** [comment]
This is a CDM WG issue.
