### ISSUE TITLE
Cohort table lacks ETL guidance 

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Themis#77]
**Issue Name:** The COHORT table doesn’t have information in the User Guide and ETL Conventions sections.

**Issue Type:** Lack of ETL conventions and User Guide information for the COHORT table and its fields.

**Description:** The missing documentation is seen here: https://ohdsi.github.io/CommonDataModel/cdm54.html#COHORT 

**Related forum post:** [Linked](https://forums.ohdsi.org/t/cohort-table-questions/18685)

**Reported By:** Melanie Philofsky

**Comment by MelaniePhilofsky** [comment]
### Proposed guidance:

Themis issue #1: COHORT table documentation updates

**COHORT – ETL Conventions how to ETL**

_Cohort_definition_id:_  The cohort_definition_id is the foreign key to the COHORT_DEFINITION table which defines the cohort this subject belongs to. 

_Subject_id:_ The subject_id can refer to the identifier for a Person, Provider, Visit, or Care Site record. Refer to the COHORT_DEFINITION.subject_concept_id field for the table which the subject belongs to.

_Cohort_start_date:_ The date the subject entered the cohort.

_Cohort_end_date:_ The date the subject left the cohort.

**COHORT – User Guide how to use this field in research/analysis**

_Cohort_definition_id:_  Reference the COHORT_DEFINITION table for the description of this cohort

**ETL conventions paragraph section**

_Change this:_
This line “A subject can only have one record in the cohort table for any moment of time, i.e. it is not possible for a person to contain multiple records indicating cohort membership that are overlapping in time” isn’t very clear.

_Change to:_ 
“The subject of a cohort can have multiple, discrete records in the cohort table per cohort_definition_id, subject_id, and non-overlapping time periods.”

**Comment by clairblacketer** [comment]
Closing as this was incorporated into the CDM docs
