### ISSUE TITLE
Multiple genders

### ISSUE THREAD

**Issue by aostropolets** [OHDSI/Themis#8]
TYPE | NOTES
-- | --
ITEM | How do we handle multiple genders?
FORUM POST | http://forums.ohdsi.org/t/should-transgenders-be-excluded-from-the-cdm/2750/13
SOLUTION | If there are multiple genders for an individual and you cannot determine if it was because of a sex change, then take the use the latest value
NEXT STEPS | Update the CDM Wiki on PERSON.gender_concept_id column Description.

**Comment by ericaVoss** [comment]
The same as #34
