### ISSUE TITLE
Drug_exposure_end_date  when verbatim_end_date and days_supply are misaligned

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Themis#87]
# What to do when the verbatim_end_date and days_supply are misaligned

## CDM or THEMIS convention?
THEMIS

## Summary of issues

- Drug_exposure_end_date is mandatory
- There are times when the days_supply of the intended dose is different than the time the patient _actually_ took the drug
- There is a question on how the days supply and drug_exposure_end_date should be populated in these cases. Should days_supply be shortened to reflect the time the patient actually took the drug? Should drug_exposure_end_date reflect the verbatim_end_date or days_supply?

## Summary of answer

- verbatim_end_date should reflect (to the best knowledge) the time that the patient was exposed to the drug
- Verbatim_end_date should also be mapped to drug_exposure_end_date
- days_supply should reflect the intent of the provider, even if the patient did not take the drug for that long, it should not be changed

## Related links

- [Forum post](https://forums.ohdsi.org/t/drug-exposure-quantity-recalculation/9607)

**Comment by clairblacketer** [comment]
# What to do when the verbatim_end_date and days_supply are misaligned

## CDM or THEMIS convention?
THEMIS

## Summary of issues

- Drug_exposure_end_date is mandatory
- There are times when the days_supply of the intended dose is different than the time the patient _actually_ took the drug
- There is a question on how the days supply should be populated in these cases. Should it be shortened to reflect the time the patient actually took the drug?

## Summary of answer

- verbatim_end_date should reflect (to the best knowledge) the time that the patient was exposed to the drug
- days_supply should reflect the intent of the provider, even if the patient did not take the drug for that long, it should not be changed

## Related links

- [Forum post](https://forums.ohdsi.org/t/drug-exposure-quantity-recalculation/9607)

**Comment by burrowse** [comment]
@clairblacketer Looks like this one moved around quite a bit haha, do we want to move this to needs more work?

**Comment by clairblacketer** [comment]
closing this as it has already been added
