### ISSUE TITLE
How to populate month_of_birth when it is not provided in the source

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Themis#95]
# How to populate month_of_birth when it is not provided in the source

## CDM or THEMIS convention?
Themis

## Is this a general convention?
No

## Summary of issues

- Month of Birth is not required in the CDM, but it is a component of birth_datetime. The CDM conventions has guidance listed for how to infer month_of_birth in the birth_datetime field but not for the month_of_birth field itself.

## Summary of answer

- If month_of_birth is null or if day_of_birth AND month_of_birth are both null and the person has records during their year of birth then use the date of the earliest record, otherwise use the 15th of June of that year.

## Related links

- CDM Website: https://ohdsi.github.io/CommonDataModel/cdm54.html#person

## Other comments/notes

- @clairblacketer @MelaniePhilofsky would appreciate your feedback on if/how we handle this one. I will be opening a similar one for day_of_birth.

**Comment by burrowse** [comment]
> @burrowse The convention is correct for how we typically assign month at birth. I usually reserve this for kids and babies for whom we observe records during their year of birth, as you note. This is helpful for mother-child linkage algorithms, perhaps we put a note to that effect?

Okay, great! That makes sense to me! This was mostly making sure that we were aligned across the month_of_birth,  day_of_birth and birth_datetime field in terms of how to infer a value as a convention.

**Comment by clairblacketer** [comment]
## Issue # and location

- [Themis issue #94](https://github.com/OHDSI/Themis/issues/94)

## Issue summary
How should month_of_birth be populated when it is not provided in the source data? Month of Birth is not required in the CDM, but it is a component of birth_datetime. 

## Convention type
Table

## CDM table
`person`

## CDM field
`month_of_birth`

## Links to issue discussion
NA

## Provenance of data
General

## The ratified convention
If month_of_birth is null or if day_of_birth AND month_of_birth are both null and the person has records during their year of birth then use the date of the earliest record, otherwise use the 15th of June of that year. This field is not required in the CDM so only impute if the required information is available. 

## Date of ratification/published
NA

## Downstream implications
No

## Link to DQD check
NA

## Related conventions/further information
NA

**#Tags**
birth_date, month_of_birth

**Comment by MelaniePhilofsky** [comment]
Edited to match wording of day_of_birth issue.

**Comment by clairblacketer** [comment]
https://github.com/OHDSI/Themis/pull/150

**Comment by clairblacketer** [comment]
reopening for discussion as we may not need to give a convention for a not-required field

tagging @cgreich @MelaniePhilofsky

**Comment by MelaniePhilofsky** [comment]
Issue has been resolved.
