### ISSUE TITLE
How to populate day_of_birth when it is not provided in the source

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Themis#96]
# How to populate day_of_birth when it is not provided in the source

## CDM or THEMIS convention?
Themis

## Is this a general convention?
No

## Summary of issues

- Day of Birth is not required in the CDM, but it is a component of birth_datetime. The CDM conventions has guidance listed for how to infer day_of_birth in the birth_datetime field but not for the day_of_birth field itself.

## Summary of answer

- If day_of_birth is null and month_of_birth is not null then use the first of the month in that year.
- If month_of_birth is null or if day_of_birth AND month_of_birth are both null and the person has records during their year of birth then use the date of the earliest record, otherwise use the 15th of June of that year.

## Related links

- CDM Website: https://ohdsi.github.io/CommonDataModel/cdm54.html#person

## Other comments/notes

- @clairblacketer @MelaniePhilofsky similar to month_of_birth, would appreciate your feedback on if/how we handle this one as well.

**Comment by clairblacketer** [comment]
PR: https://github.com/OHDSI/Themis/pull/149

**Comment by clairblacketer** [comment]
Reopening as it may not be necessary to provide guidance on imputing a field that is not required

**Comment by MelaniePhilofsky** [comment]
This issue has been resolved.
