### ISSUE TITLE
How to choose a provider in the person table if there are multiple options

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Themis#97]
**Issue Name:** How to choose a provider in the person table if there are multiple options

**Issue Type:** Lack of convention

**Description:** In the CDM documentation for PERSON.provider_id, it says:
<img width="519" alt="image" src="https://github.com/OHDSI/Themis/assets/12911960/b6c0d896-d733-4288-83e4-d2f5053b1f9d">

but there is no guidance on how to choose a provider, just that the ETL should choose.

**Related forum post:** None

**Suggested solution:** I am not sure what it would look like for there to be multiple options for this field, perhaps we just remove this line from the CDM documentation until there is a use case or data to support it.

**Reported By:** Clair Blacketer

**Comment by MelaniePhilofsky** [comment]
@clairblacketer 

This should be the person's primary care provider. The clinical events will have the provider for each visit/event. Thoughts?
