### ISSUE TITLE
How to document multiple causes of death

### ISSUE THREAD

**Issue by askanter** [OHDSI/Themis#98]
# Multiple Death Records Due to Death_type_concept or Cause_concept Version 5.4

## CDM or THEMIS convention?

![Image](https://github.com/OHDSI/Themis/assets/24284566/85db7330-ea05-4776-91e7-4a89a50ea4da)

## Is this a general convention?
Does this convention apply to the model at large or perhaps applies to multiple fields (i.e. how datetimes are represented)

No.

## Summary of issues

- Write out some of the questions that this convention is meant to address

There are two reasons why there might be more than one cause of death for a patient. 
1) There can be multiple different causes of death depending on the source.
2) A single source cause of death might map to multiple standard codes.

## Summary of answer

- Based on your findings, give a few bullets on what the community decided
1) If multiple death records occur, the date and the person have to be the same, but the cause can be different. Can be reported by different sources as well. https://github.com/OHDSI/Themis/issues/5
2) For OMOP version 5.4, allow multiple records in the Death table caused by either the death_type_concept_id and/or cause_concept_id. However the Death_Date(s) must match. https://github.com/OHDSI/Themis/issues/79 (open)

## Related links

https://forums.ohdsi.org/t/themis-conventions-for-death-table-to-allow-multiple-records-version-5-4/19992
https://github.com/OHDSI/Themis/issues/79 (open)

https://github.com/OHDSI/Themis/issues/5   (CLOSED)

https://github.com/OHDSI/CommonDataModel/issues/209 (open)

## Other comments/notes

- Please use this section to add any other relevant notes or comments. (i.e. if links are not working, something is out of date or  deprecated)

**Comment by clairblacketer** [comment]
In this case the answer conflicts with the expectations of the DEATH table in CDM v5.4: 

![Image](https://github.com/OHDSI/Themis/assets/12911960/ebac6608-d205-45a5-ab0e-1054b13c84e5)

In the documentation we say a person can have only one death record but then this ratified Themis convention #5 suggests a person can have multiple records in the DEATH table with different causes as long as they have the same date. We debated this extensively in the lead up to [CDM v6.0](https://github.com/OHDSI/CommonDataModel/issues/210). I think these points still stand even through the lens of keeping the DEATH table. My concern is in my understanding around how ATLAS looks for death if it is included in a cohort definition. I believe CIRCE assumes only one record per person in the DEATH table.  @chrisknoll can you confirm? 

Up to this point we have suggested that a person has only one record in the DEATH table and any other causes of death should be captured in the CONDITION_OCCURRENCE table with a [type concept id](https://athena.ohdsi.org/search-terms/terms?vocabulary=Type+Concept&page=1&pageSize=15&query=death&boosts) denoting it is related to the person's death. I would prefer to keep that convention until such time we make a decision on Themis #79 .

@MelaniePhilofsky what are your thoughts?

**Comment by clairblacketer** [comment]
@askanter I am going to move this back to in progress while we wait to hear from others.

**Comment by askanter** [comment]
Ok, there does seem to need some work here. In the case of official causes of death, there can be more than one condition noted. They are typically listed in order, with the final cause of death something like cardiopulmonary arrest. There can then be contributing factors such as ARDS and COVID-19. This is the first example where the ETL process needs guidance if they have to select one of these three.

The second case is still open, which is when the cause_source_concept_id is mapped to multiple standard codes. Which standard code should be used?

**Comment by clairblacketer** [comment]
@askanter I agree we have some work to do. I am going to move this out of the April Olympians project for now but it will remain as a Themis issue so we will not lose your research

**Comment by askanter** [comment]
Added comments to existing Themis issue 79
